-- Delete a column name location from movie_theatre

ALTER TABLE MOVIE_THEATRE
DROP COLUMN LOCATION;

DESC MOVIE_THEATRE

/*
Column	Null?	Type
THEATRE_NAME	 - 	VARCHAR2(20)
NO_OF_SEATS	 - 	NUMBER(3,0)
TICKET_PRICE	 - 	NUMBER(5,2)
*/